
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Syntax;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DIVIDE = 14;
  public static final int DELIMITER = 12;
  public static final int SCOPE_END = 18;
  public static final int CHAR = 6;
  public static final int CASTRIGHT = 38;
  public static final int GET_CHAR = 10;
  public static final int CONTINUE = 29;
  public static final int INT = 11;
  public static final int INTNUM = 35;
  public static final int FOR = 26;
  public static final int MINUS = 13;
  public static final int BRACKET_RIGHT = 5;
  public static final int GREATER_THAN = 17;
  public static final int BRACKET_LEFT = 4;
  public static final int NOT = 30;
  public static final int AND = 31;
  public static final int OR = 24;
  public static final int LESS_EQUAL = 20;
  public static final int ASSIGN = 9;
  public static final int IF = 22;
  public static final int ID = 21;
  public static final int EOF = 0;
  public static final int GREATER_EQUAL = 15;
  public static final int error = 1;
  public static final int ADD = 3;
  public static final int MOD = 23;
  public static final int NEQ = 34;
  public static final int CHARNUM = 37;
  public static final int BREAK = 16;
  public static final int REALNUM = 36;
  public static final int EQ = 28;
  public static final int REAL = 32;
  public static final int TIMES = 25;
  public static final int ELSE = 19;
  public static final int WHILE = 33;
  public static final int SCOPE_START = 7;
  public static final int LESS_THAN = 27;
  public static final int PRINT = 2;
  public static final int DO = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "ADD",
  "BRACKET_LEFT",
  "BRACKET_RIGHT",
  "CHAR",
  "SCOPE_START",
  "DO",
  "ASSIGN",
  "GET_CHAR",
  "INT",
  "DELIMITER",
  "MINUS",
  "DIVIDE",
  "GREATER_EQUAL",
  "BREAK",
  "GREATER_THAN",
  "SCOPE_END",
  "ELSE",
  "LESS_EQUAL",
  "ID",
  "IF",
  "MOD",
  "OR",
  "TIMES",
  "FOR",
  "LESS_THAN",
  "EQ",
  "CONTINUE",
  "NOT",
  "AND",
  "REAL",
  "WHILE",
  "NEQ",
  "INTNUM",
  "REALNUM",
  "CHARNUM",
  "CASTRIGHT"
  };
}

