
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 15;
  public static final int MOD = 17;
  public static final int AND = 22;
  public static final int CONTINUE = 12;
  public static final int ELSE = 7;
  public static final int DELIMITER = 31;
  public static final int OR = 23;
  public static final int LESS_EQUAL = 20;
  public static final int INT = 4;
  public static final int BRACKET_LEFT = 29;
  public static final int GREATER_THAN = 19;
  public static final int WHILE = 8;
  public static final int NOT = 24;
  public static final int GREATER_EQUAL = 21;
  public static final int intnum = 2;
  public static final int IF = 6;
  public static final int ID = 33;
  public static final int SCOPE_END = 27;
  public static final int DO = 9;
  public static final int EOF = 0;
  public static final int DIVIDE = 16;
  public static final int LESS_THAN = 18;
  public static final int BREAK = 11;
  public static final int ADD = 13;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int ASSIGN = 28;
  public static final int EQ = 25;
  public static final int realnum = 3;
  public static final int BRACKET_RIGHT = 30;
  public static final int FOR = 10;
  public static final int REAL = 5;
  public static final int NEQ = 32;
  public static final int SCOPE_START = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "intnum",
  "realnum",
  "INT",
  "REAL",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "BREAK",
  "CONTINUE",
  "ADD",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "LESS_THAN",
  "GREATER_THAN",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "AND",
  "OR",
  "NOT",
  "EQ",
  "SCOPE_START",
  "SCOPE_END",
  "ASSIGN",
  "BRACKET_LEFT",
  "BRACKET_RIGHT",
  "DELIMITER",
  "NEQ",
  "ID"
  };
}

